version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
    volumes:
      - /user/ubuntu/db_data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"

  notes-app:
    image: roshanx/django-notes-app:latest
    container_name: notes-app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      DB_NAME: devops
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: mysql
      DB_PORT: 3306
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
